# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlos/Grpc/MlosCommonMessageTypes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlos/Grpc/MlosCommonMessageTypes.proto',
  package='mlos_common_message_types',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&mlos/Grpc/MlosCommonMessageTypes.proto\x12\x19mlos_common_message_types\"\x87\x02\n\x13OptimizationProblem\x12<\n\x0eParameterSpace\x18\x01 \x01(\x0b\x32$.mlos_common_message_types.Hypergrid\x12:\n\x0c\x43ontextSpace\x18\x02 \x01(\x0b\x32$.mlos_common_message_types.Hypergrid\x12<\n\x0eObjectiveSpace\x18\x03 \x01(\x0b\x32$.mlos_common_message_types.Hypergrid\x12\x38\n\nObjectives\x18\x04 \x03(\x0b\x32$.mlos_common_message_types.Objective\"\x1d\n\x0fOptimizerHandle\x12\n\n\x02Id\x18\x01 \x01(\t\"\xc4\x01\n\rOptimizerInfo\x12\x43\n\x0fOptimizerHandle\x18\x01 \x01(\x0b\x32*.mlos_common_message_types.OptimizerHandle\x12!\n\x19OptimizerConfigJsonString\x18\x02 \x01(\t\x12K\n\x13OptimizationProblem\x18\x03 \x01(\x0b\x32..mlos_common_message_types.OptimizationProblem\"\x89\x01\n\x0bObservation\x12\x35\n\x08\x46\x65\x61tures\x18\x01 \x01(\x0b\x32#.mlos_common_message_types.Features\x12\x43\n\x0fObjectiveValues\x18\x02 \x01(\x0b\x32*.mlos_common_message_types.ObjectiveValues\"\x8a\x01\n\x0cObservations\x12\x35\n\x08\x46\x65\x61tures\x18\x01 \x01(\x0b\x32#.mlos_common_message_types.Features\x12\x43\n\x0fObjectiveValues\x18\x02 \x01(\x0b\x32*.mlos_common_message_types.ObjectiveValues\"&\n\x08\x46\x65\x61tures\x12\x1a\n\x12\x46\x65\x61turesJsonString\x18\x01 \x01(\t\"7\n\x17\x43onfigurationParameters\x12\x1c\n\x14ParametersJsonString\x18\x01 \x01(\t\"$\n\x07\x43ontext\x12\x19\n\x11\x43ontextJsonString\x18\x01 \x01(\t\"4\n\x0fObjectiveValues\x12!\n\x19ObjectiveValuesJsonString\x18\x01 \x01(\t\"(\n\tHypergrid\x12\x1b\n\x13HypergridJsonString\x18\x01 \x01(\t\"+\n\tObjective\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x08Minimize\x18\x02 \x01(\x08\"\x1e\n\rSimpleBoolean\x12\r\n\x05Value\x18\x01 \x01(\x08\"\x1d\n\x0cSimpleString\x12\r\n\x05Value\x18\x01 \x01(\t\"\x07\n\x05\x45mptyb\x06proto3'
)




_OPTIMIZATIONPROBLEM = _descriptor.Descriptor(
  name='OptimizationProblem',
  full_name='mlos_common_message_types.OptimizationProblem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ParameterSpace', full_name='mlos_common_message_types.OptimizationProblem.ParameterSpace', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ContextSpace', full_name='mlos_common_message_types.OptimizationProblem.ContextSpace', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectiveSpace', full_name='mlos_common_message_types.OptimizationProblem.ObjectiveSpace', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Objectives', full_name='mlos_common_message_types.OptimizationProblem.Objectives', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=333,
)


_OPTIMIZERHANDLE = _descriptor.Descriptor(
  name='OptimizerHandle',
  full_name='mlos_common_message_types.OptimizerHandle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='mlos_common_message_types.OptimizerHandle.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=364,
)


_OPTIMIZERINFO = _descriptor.Descriptor(
  name='OptimizerInfo',
  full_name='mlos_common_message_types.OptimizerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OptimizerHandle', full_name='mlos_common_message_types.OptimizerInfo.OptimizerHandle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OptimizerConfigJsonString', full_name='mlos_common_message_types.OptimizerInfo.OptimizerConfigJsonString', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OptimizationProblem', full_name='mlos_common_message_types.OptimizerInfo.OptimizationProblem', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=563,
)


_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='mlos_common_message_types.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Features', full_name='mlos_common_message_types.Observation.Features', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectiveValues', full_name='mlos_common_message_types.Observation.ObjectiveValues', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=703,
)


_OBSERVATIONS = _descriptor.Descriptor(
  name='Observations',
  full_name='mlos_common_message_types.Observations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Features', full_name='mlos_common_message_types.Observations.Features', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectiveValues', full_name='mlos_common_message_types.Observations.ObjectiveValues', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=706,
  serialized_end=844,
)


_FEATURES = _descriptor.Descriptor(
  name='Features',
  full_name='mlos_common_message_types.Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='FeaturesJsonString', full_name='mlos_common_message_types.Features.FeaturesJsonString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=846,
  serialized_end=884,
)


_CONFIGURATIONPARAMETERS = _descriptor.Descriptor(
  name='ConfigurationParameters',
  full_name='mlos_common_message_types.ConfigurationParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ParametersJsonString', full_name='mlos_common_message_types.ConfigurationParameters.ParametersJsonString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=886,
  serialized_end=941,
)


_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='mlos_common_message_types.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ContextJsonString', full_name='mlos_common_message_types.Context.ContextJsonString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=943,
  serialized_end=979,
)


_OBJECTIVEVALUES = _descriptor.Descriptor(
  name='ObjectiveValues',
  full_name='mlos_common_message_types.ObjectiveValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ObjectiveValuesJsonString', full_name='mlos_common_message_types.ObjectiveValues.ObjectiveValuesJsonString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=981,
  serialized_end=1033,
)


_HYPERGRID = _descriptor.Descriptor(
  name='Hypergrid',
  full_name='mlos_common_message_types.Hypergrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='HypergridJsonString', full_name='mlos_common_message_types.Hypergrid.HypergridJsonString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1035,
  serialized_end=1075,
)


_OBJECTIVE = _descriptor.Descriptor(
  name='Objective',
  full_name='mlos_common_message_types.Objective',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='mlos_common_message_types.Objective.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Minimize', full_name='mlos_common_message_types.Objective.Minimize', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1077,
  serialized_end=1120,
)


_SIMPLEBOOLEAN = _descriptor.Descriptor(
  name='SimpleBoolean',
  full_name='mlos_common_message_types.SimpleBoolean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='mlos_common_message_types.SimpleBoolean.Value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1122,
  serialized_end=1152,
)


_SIMPLESTRING = _descriptor.Descriptor(
  name='SimpleString',
  full_name='mlos_common_message_types.SimpleString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='mlos_common_message_types.SimpleString.Value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1154,
  serialized_end=1183,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='mlos_common_message_types.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1185,
  serialized_end=1192,
)

_OPTIMIZATIONPROBLEM.fields_by_name['ParameterSpace'].message_type = _HYPERGRID
_OPTIMIZATIONPROBLEM.fields_by_name['ContextSpace'].message_type = _HYPERGRID
_OPTIMIZATIONPROBLEM.fields_by_name['ObjectiveSpace'].message_type = _HYPERGRID
_OPTIMIZATIONPROBLEM.fields_by_name['Objectives'].message_type = _OBJECTIVE
_OPTIMIZERINFO.fields_by_name['OptimizerHandle'].message_type = _OPTIMIZERHANDLE
_OPTIMIZERINFO.fields_by_name['OptimizationProblem'].message_type = _OPTIMIZATIONPROBLEM
_OBSERVATION.fields_by_name['Features'].message_type = _FEATURES
_OBSERVATION.fields_by_name['ObjectiveValues'].message_type = _OBJECTIVEVALUES
_OBSERVATIONS.fields_by_name['Features'].message_type = _FEATURES
_OBSERVATIONS.fields_by_name['ObjectiveValues'].message_type = _OBJECTIVEVALUES
DESCRIPTOR.message_types_by_name['OptimizationProblem'] = _OPTIMIZATIONPROBLEM
DESCRIPTOR.message_types_by_name['OptimizerHandle'] = _OPTIMIZERHANDLE
DESCRIPTOR.message_types_by_name['OptimizerInfo'] = _OPTIMIZERINFO
DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['Observations'] = _OBSERVATIONS
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
DESCRIPTOR.message_types_by_name['ConfigurationParameters'] = _CONFIGURATIONPARAMETERS
DESCRIPTOR.message_types_by_name['Context'] = _CONTEXT
DESCRIPTOR.message_types_by_name['ObjectiveValues'] = _OBJECTIVEVALUES
DESCRIPTOR.message_types_by_name['Hypergrid'] = _HYPERGRID
DESCRIPTOR.message_types_by_name['Objective'] = _OBJECTIVE
DESCRIPTOR.message_types_by_name['SimpleBoolean'] = _SIMPLEBOOLEAN
DESCRIPTOR.message_types_by_name['SimpleString'] = _SIMPLESTRING
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimizationProblem = _reflection.GeneratedProtocolMessageType('OptimizationProblem', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZATIONPROBLEM,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.OptimizationProblem)
  })
_sym_db.RegisterMessage(OptimizationProblem)

OptimizerHandle = _reflection.GeneratedProtocolMessageType('OptimizerHandle', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERHANDLE,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.OptimizerHandle)
  })
_sym_db.RegisterMessage(OptimizerHandle)

OptimizerInfo = _reflection.GeneratedProtocolMessageType('OptimizerInfo', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERINFO,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.OptimizerInfo)
  })
_sym_db.RegisterMessage(OptimizerInfo)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATION,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.Observation)
  })
_sym_db.RegisterMessage(Observation)

Observations = _reflection.GeneratedProtocolMessageType('Observations', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATIONS,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.Observations)
  })
_sym_db.RegisterMessage(Observations)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), {
  'DESCRIPTOR' : _FEATURES,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.Features)
  })
_sym_db.RegisterMessage(Features)

ConfigurationParameters = _reflection.GeneratedProtocolMessageType('ConfigurationParameters', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONPARAMETERS,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.ConfigurationParameters)
  })
_sym_db.RegisterMessage(ConfigurationParameters)

Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.Context)
  })
_sym_db.RegisterMessage(Context)

ObjectiveValues = _reflection.GeneratedProtocolMessageType('ObjectiveValues', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTIVEVALUES,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.ObjectiveValues)
  })
_sym_db.RegisterMessage(ObjectiveValues)

Hypergrid = _reflection.GeneratedProtocolMessageType('Hypergrid', (_message.Message,), {
  'DESCRIPTOR' : _HYPERGRID,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.Hypergrid)
  })
_sym_db.RegisterMessage(Hypergrid)

Objective = _reflection.GeneratedProtocolMessageType('Objective', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTIVE,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.Objective)
  })
_sym_db.RegisterMessage(Objective)

SimpleBoolean = _reflection.GeneratedProtocolMessageType('SimpleBoolean', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEBOOLEAN,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.SimpleBoolean)
  })
_sym_db.RegisterMessage(SimpleBoolean)

SimpleString = _reflection.GeneratedProtocolMessageType('SimpleString', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLESTRING,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.SimpleString)
  })
_sym_db.RegisterMessage(SimpleString)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'mlos.Grpc.MlosCommonMessageTypes_pb2'
  # @@protoc_insertion_point(class_scope:mlos_common_message_types.Empty)
  })
_sym_db.RegisterMessage(Empty)


# @@protoc_insertion_point(module_scope)
