# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlos/Grpc/OptimizerMonitoringService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlos.Grpc import OptimizerShared_pb2 as mlos_dot_Grpc_dot_OptimizerShared__pb2

from mlos.Grpc.OptimizerShared_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlos/Grpc/OptimizerMonitoringService.proto',
  package='mlos.optimizer_monitoring_service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*mlos/Grpc/OptimizerMonitoringService.proto\x12!mlos.optimizer_monitoring_service\x1a\x1fmlos/Grpc/OptimizerShared.proto\"s\n\x19OptimizerConvergenceState\x12)\n\x0fOptimizerHandle\x18\x01 \x01(\x0b\x32\x10.OptimizerHandle\x12+\n#SerializedOptimizerConvergenceState\x18\x02 \x01(\t\"3\n\rOptimizerList\x12\"\n\nOptimizers\x18\x01 \x03(\x0b\x32\x0e.OptimizerInfo\"X\n\x0ePredictRequest\x12)\n\x0fOptimizerHandle\x18\x01 \x01(\x0b\x32\x10.OptimizerHandle\x12\x1b\n\x08\x46\x65\x61tures\x18\x02 \x01(\x0b\x32\t.Features\"Y\n\x19SingleObjectivePrediction\x12\x15\n\rObjectiveName\x18\x01 \x01(\t\x12%\n\x1dPredictionDataFrameJsonString\x18\x02 \x01(\t\"m\n\x0fPredictResponse\x12Z\n\x14ObjectivePredictions\x18\x01 \x03(\x0b\x32<.mlos.optimizer_monitoring_service.SingleObjectivePrediction2\x84\x05\n\x1aOptimizerMonitoringService\x12R\n\x16ListExistingOptimizers\x12\x06.Empty\x1a\x30.mlos.optimizer_monitoring_service.OptimizerList\x12\x34\n\x10GetOptimizerInfo\x12\x10.OptimizerHandle\x1a\x0e.OptimizerInfo\x12n\n\x1cGetOptimizerConvergenceState\x12\x10.OptimizerHandle\x1a<.mlos.optimizer_monitoring_service.OptimizerConvergenceState\x12>\n\x1b\x43omputeGoodnessOfFitMetrics\x12\x10.OptimizerHandle\x1a\r.SimpleString\x12-\n\tIsTrained\x12\x10.OptimizerHandle\x1a\x0e.SimpleBoolean\x12<\n\x14RegisterObservations\x12\x1c.RegisterObservationsRequest\x1a\x06.Empty\x12p\n\x07Predict\x12\x31.mlos.optimizer_monitoring_service.PredictRequest\x1a\x32.mlos.optimizer_monitoring_service.PredictResponse\x12\x35\n\x12GetAllObservations\x12\x10.OptimizerHandle\x1a\r.Observations\x12\x16\n\x04\x45\x63ho\x12\x06.Empty\x1a\x06.EmptyP\x00\x62\x06proto3'
  ,
  dependencies=[mlos_dot_Grpc_dot_OptimizerShared__pb2.DESCRIPTOR,],
  public_dependencies=[mlos_dot_Grpc_dot_OptimizerShared__pb2.DESCRIPTOR,])




_OPTIMIZERCONVERGENCESTATE = _descriptor.Descriptor(
  name='OptimizerConvergenceState',
  full_name='mlos.optimizer_monitoring_service.OptimizerConvergenceState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OptimizerHandle', full_name='mlos.optimizer_monitoring_service.OptimizerConvergenceState.OptimizerHandle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SerializedOptimizerConvergenceState', full_name='mlos.optimizer_monitoring_service.OptimizerConvergenceState.SerializedOptimizerConvergenceState', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=229,
)


_OPTIMIZERLIST = _descriptor.Descriptor(
  name='OptimizerList',
  full_name='mlos.optimizer_monitoring_service.OptimizerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Optimizers', full_name='mlos.optimizer_monitoring_service.OptimizerList.Optimizers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=282,
)


_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='mlos.optimizer_monitoring_service.PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OptimizerHandle', full_name='mlos.optimizer_monitoring_service.PredictRequest.OptimizerHandle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Features', full_name='mlos.optimizer_monitoring_service.PredictRequest.Features', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=372,
)


_SINGLEOBJECTIVEPREDICTION = _descriptor.Descriptor(
  name='SingleObjectivePrediction',
  full_name='mlos.optimizer_monitoring_service.SingleObjectivePrediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ObjectiveName', full_name='mlos.optimizer_monitoring_service.SingleObjectivePrediction.ObjectiveName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PredictionDataFrameJsonString', full_name='mlos.optimizer_monitoring_service.SingleObjectivePrediction.PredictionDataFrameJsonString', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=463,
)


_PREDICTRESPONSE = _descriptor.Descriptor(
  name='PredictResponse',
  full_name='mlos.optimizer_monitoring_service.PredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ObjectivePredictions', full_name='mlos.optimizer_monitoring_service.PredictResponse.ObjectivePredictions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=574,
)

_OPTIMIZERCONVERGENCESTATE.fields_by_name['OptimizerHandle'].message_type = mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERHANDLE
_OPTIMIZERLIST.fields_by_name['Optimizers'].message_type = mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERINFO
_PREDICTREQUEST.fields_by_name['OptimizerHandle'].message_type = mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERHANDLE
_PREDICTREQUEST.fields_by_name['Features'].message_type = mlos_dot_Grpc_dot_OptimizerShared__pb2._FEATURES
_PREDICTRESPONSE.fields_by_name['ObjectivePredictions'].message_type = _SINGLEOBJECTIVEPREDICTION
DESCRIPTOR.message_types_by_name['OptimizerConvergenceState'] = _OPTIMIZERCONVERGENCESTATE
DESCRIPTOR.message_types_by_name['OptimizerList'] = _OPTIMIZERLIST
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['SingleObjectivePrediction'] = _SINGLEOBJECTIVEPREDICTION
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimizerConvergenceState = _reflection.GeneratedProtocolMessageType('OptimizerConvergenceState', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERCONVERGENCESTATE,
  '__module__' : 'mlos.Grpc.OptimizerMonitoringService_pb2'
  # @@protoc_insertion_point(class_scope:mlos.optimizer_monitoring_service.OptimizerConvergenceState)
  })
_sym_db.RegisterMessage(OptimizerConvergenceState)

OptimizerList = _reflection.GeneratedProtocolMessageType('OptimizerList', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERLIST,
  '__module__' : 'mlos.Grpc.OptimizerMonitoringService_pb2'
  # @@protoc_insertion_point(class_scope:mlos.optimizer_monitoring_service.OptimizerList)
  })
_sym_db.RegisterMessage(OptimizerList)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'mlos.Grpc.OptimizerMonitoringService_pb2'
  # @@protoc_insertion_point(class_scope:mlos.optimizer_monitoring_service.PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)

SingleObjectivePrediction = _reflection.GeneratedProtocolMessageType('SingleObjectivePrediction', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEOBJECTIVEPREDICTION,
  '__module__' : 'mlos.Grpc.OptimizerMonitoringService_pb2'
  # @@protoc_insertion_point(class_scope:mlos.optimizer_monitoring_service.SingleObjectivePrediction)
  })
_sym_db.RegisterMessage(SingleObjectivePrediction)

PredictResponse = _reflection.GeneratedProtocolMessageType('PredictResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTRESPONSE,
  '__module__' : 'mlos.Grpc.OptimizerMonitoringService_pb2'
  # @@protoc_insertion_point(class_scope:mlos.optimizer_monitoring_service.PredictResponse)
  })
_sym_db.RegisterMessage(PredictResponse)



_OPTIMIZERMONITORINGSERVICE = _descriptor.ServiceDescriptor(
  name='OptimizerMonitoringService',
  full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=577,
  serialized_end=1221,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListExistingOptimizers',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.ListExistingOptimizers',
    index=0,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._EMPTY,
    output_type=_OPTIMIZERLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOptimizerInfo',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.GetOptimizerInfo',
    index=1,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERHANDLE,
    output_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOptimizerConvergenceState',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.GetOptimizerConvergenceState',
    index=2,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERHANDLE,
    output_type=_OPTIMIZERCONVERGENCESTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ComputeGoodnessOfFitMetrics',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.ComputeGoodnessOfFitMetrics',
    index=3,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERHANDLE,
    output_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._SIMPLESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsTrained',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.IsTrained',
    index=4,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERHANDLE,
    output_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._SIMPLEBOOLEAN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterObservations',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.RegisterObservations',
    index=5,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._REGISTEROBSERVATIONSREQUEST,
    output_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.Predict',
    index=6,
    containing_service=None,
    input_type=_PREDICTREQUEST,
    output_type=_PREDICTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllObservations',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.GetAllObservations',
    index=7,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._OPTIMIZERHANDLE,
    output_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._OBSERVATIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='mlos.optimizer_monitoring_service.OptimizerMonitoringService.Echo',
    index=8,
    containing_service=None,
    input_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._EMPTY,
    output_type=mlos_dot_Grpc_dot_OptimizerShared__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPTIMIZERMONITORINGSERVICE)

DESCRIPTOR.services_by_name['OptimizerMonitoringService'] = _OPTIMIZERMONITORINGSERVICE

# @@protoc_insertion_point(module_scope)
